[mgr]

ratio = [1, 3, 3]
sort_by = 'alphabetical'
linemode = 'size_and_mtime'
show_hidden = true
show_symlink = true

[opener]

edit = [
  {run = 'nvim $@', block = true, for = 'unix'}
]

[preview]
wrap = "yes"


